name: Build & Deploy API Docs

on:
  push:
    # trigger on changes to your OpenAPI JSON (or this workflow)
    paths:
      - 'openapi/**/*.json'
      - '.github/workflows/deploy-docs.yml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'      # any LTS version

      - name: Install ReDoc CLI
        run: npm install -g @redocly/cli

      - name: Bundle OpenAPI with ReDoc
        run: |
          redoc-cli bundle \
            openapi/soko-rest-openapi.json \
            --title "Soko3 REST API" \
            --options.nativeScrollbars \
            -o api-docs.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          # if you only want to deploy api-docs.html, you could set:
          # publish_dir: .
          # include: |
          #   api-docs.html
